export class Product{
    name!:string;
    title!:string;
    subTitle!:string;
    sku!:string;
    isbn!:string;
    isbn10!:string;
    projectNo!:number;
    id!:string;
    ownership!:string;
    versionType!:string;
    bindingStyle!:string;
    subGroup!:string;
    salesEval!:string;
    imprint!:string;
    publisher!:string;
    metatags!:string;
    description!:string;
    features!:string[];
    reviews!:string;
    gtUpdate!:string;
    pubDate!:string;
    copyRight!:string;
    homeDiscountCode!:string;
    editionNo!:number;
    pages!:number;
    isBestSeller!:boolean;
}